apiVersion: v1
kind: LimitRange
metadata:
  name: staging-zeus-limit-cpu-ram
  namespace: staging-zeus
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "1024Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    default:
      cpu: "200m"
      memory: "200Mi"
    defaultRequest:
      cpu: "200m"
      memory: "200Mi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-zeus-limit-storage
  namespace: staging-zeus
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 5Gi
    min:
      storage: 1Gi